config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :foos
  root "queries#new"

  resource :search_histories, only: [:destroy]

  resources :queries, only: [:create, :index, :new, :show] do
    resources module: :queries, only: [:create]
  end

  # delete '/search_histories', to: 'search_histories#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fake_index.rb
class FakeIndex
  def set
    {
      "example" => {
        "term" => "example",
        "results" => [
          "rank" => 1,
          "title" => "Some information you searched for",
          "url" => "https://example.com",
        ]
      }
    }
  end

  def find(term)
    set[term] || { "term" => term, "results" => [] }
  end
end

app/models/query.rb
class Query < ApplicationRecord

  delegate :results?, :results, to: :search_result

  private

  def search_result(search_engine = SearchEngine.new)
    @search_result ||= execute_search(search_engine)
  end

  def execute_search(search_engine)
    search = Search.new(query: self, search_engine: search_engine)
    search.execute
  end
end

app/models/search.rb
class Search
  def initialize(query:, search_engine:)
    @query = query
    @search_engine = search_engine
  end

  def execute
    @result = @search_engine
      .search(@query.search_term)

    self
  end

  def term
    return nil unless @result.present?

    @result["term"]
  end

  def results
    return [] unless @result.present?

    @result["results"].map { |r| SearchResult.new(r) }
  end

  def results?
    results.present?
  end
end

app/models/search_engine.rb
class SearchEngine

  def initialize(index = YamlIndex.new)
    @index = index
  end

  def search(term)
    @index.set
    @index.find(term)
  end
end

app/models/search_history.rb
class SearchHistory
  include ActiveModel::Model

  def self.clear
    Query.destroy_all
  end
end

app/models/search_result.rb
class SearchResult
  def initialize(result)
    @result = result
  end

  def rank
    @result["rank"]
  end

  def title
    @result["title"]
  end

  def url
    @result["url"]
  end

  def host
    URI(url).host
  end
end

app/models/yaml_index.rb
class YamlIndex
  def set
    @index ||= YAML
      .load_file(Rails.root.join('index.yml'))
      .each_with_object({}) do |(_k, value), hash|
        hash[value["term"]] = value
      end
  end

  def find(term)
    return no_result(term) unless defined?(@index)

    @index[term] || no_result(term)
  end

  private

  def no_result(term)
    { "term" => term, "results" => [] }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  def index
    @queries = Query
      .all
      .order(searched_at: :desc)
  end

  def new
    @query = Query.new
  end

  def create
    @query = Query.new(query_params)

    if @query.save
      redirect_to @query
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @query = Query.find(params[:id])
  end

  private

  def query_params
    params.require(:query).permit(:search_term)
  end
end

app/controllers/search_histories_controller.rb
class SearchHistoriesController < ApplicationController
  def destroy
    ClearSearchHistoryJob.perform_later

    redirect_to root_url, status: :see_other
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datetime_helper.rb
module DatetimeHelper
  def l_datetime(timestamp, placeholder: "", **opts)
    if timestamp.present?
      l(timestamp, **opts)
    else
      placeholder
    end
  end
end

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="flex items-center justify-between flex-wrap bg-primary py-3 px-6 fixed w-full z-10 top-0">
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <%= link_to root_url, class: "text-white no-underline hover:text-white hover:no-underline" do %>
          <span class="text-3xl pl-2">Helpjuice Test Project</span>
        <% end %>
      </div>

      <div class="w-full flex-grow flex items-center w-auto block pt-0" id="nav-content">
        <ul class="list-reset lg:flex justify-end flex-1 items-center">
          <li class="mr-3">
            <%= link_to "Search", root_url, class: request.path == queries_path ? "inline-block text-black no-underline hover:text-gray-200 hover:text-underline py-2 px-4" : "inline-block py-2 px-4 text-xl text-white no-underline" %>
          </li>
          <li class="mr-3">
            <%= link_to "Search History", queries_path, class: request.path == queries_path ? "inline-block py-2 px-4 text-xl text-white no-underline" : "inline-block text-black no-underline hover:text-gray-200 hover:text-underline py-2 px-4" %>
          </li>
        </ul>
      </div>
    </nav>

    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/queries/index.html.erb
<div class="flex flex-wrap w-full">
  <h1 class="w-full leading-8 text-5xl pb-3">
    Search History
  </h1>
  <div class="flex w-full items-baseline">
    <p class="text-xl pb-7 pl-3">
      Searches: <%= @queries.load.size %>
    </p>

    <%= link_to "Clear", SearchHistory.new, class: "ml-7 rounded bg-primary hover:bg-highlight text-white font-bold py-2 px-4 my-2", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  </div>

  <% @queries.each do |query| %>
    <div id="<%= dom_id query %>" class="w-full">
      <h2 class="w-full text-3xl"><%= link_to query.search_term, query, class: "underline" %></h2>
      <div class="pl-5 py-2">
        <%= render(DateAndTimeComponent.new(query.searched_at)) %>
      </div>
    </div>
  <% end %>
</div>

app/views/queries/new.html.erb
<%= form_with model: @query, class: "w-full" do |form| %>
  <div class="flex flex-wrap -mx-3 mb-6">
    <%= form.label :search_term, "Search Term", class: "hidden" %>
    <%= form.text_field :search_term, class: "block center w-10/12 rounded-l-lg appearance-none leading-8 text-5xl" %>
    <%= form.submit "Search", class: "w-2/12 rounded-r-lg bg-primary hover:bg-highlight text-white text-3xl font-bold py-2 px-4" %>
  </div>
<% end %>

app/views/queries/show.html.erb
<div id="<%= dom_id @query %>" class="flex flex-wrap w-full">
  <h1 class="w-full leading-8 text-5xl pb-10">
    <%= @query.search_term %>
  </h1>
  <% if @query.results? %>
    <ol class="w-full pl-10">
      <% @query.results.each do |result| %>
        <li class="w-full flex flex-wrap pb-5">
          <div class="text-5xl text-bold pr-3">
            <%= result.rank %>
          </div>
          <div class="pl=3 flex flex-col">
            <%= link_to result.title, result.url, class: "text-primary underline visited:decoration-highlight" %>
            <%= result.host %>
          </div>
        </li>
      <% end %>
    </ol>
  <% else %>
    <p class="w-full pl-10 text-highlight font-bold pb-7">No results found</p>
  <% end %>

  <div class="w-full pl-5 pb-5">
    <%= render(DateAndTimeComponent.new(@query.searched_at)) %>
  </div>

</div>